/*
pk - primary key - cria índice fisico na tabela - 1 por tab. - clustered index
uk - unique key - cria índice lógico na tabela - n por tab. - nonclustered index
ck - check constraint - validar os dados
*/

/*
SQL Ansi
DML - DATA MANIPULATION LANGUAGE (SELECT, INSERT, DELET, UPDATE)
DDL - DATA DEFINITION LANGUAGE(STORED PROCEDURE, TRIGGER, FUNCTION, VIEW)
*/

/* FUNÇÕES SQL SERVER
SUBSTRING - PARTE DE UMA STRING
UPPER - TRANSFORMA AS LETRAS TODAS EM MAIÚSCULAS
LOWER - CONVERTE EM MINÚSCULO
TRIM - RETIRA OS ESPAÇOS EM BRANCO DA STRING NA ESQUERDA E DIREITA
LTRIM - RETIRA OS ESPAÇOS EM BRANCO DA STRING NA ESQUERDA
RTRIM - RETIRA OS ESPAÇOS EM BRANCO DA STRING NA DIREITA
CHARINDEX - RETORNA A PRIMEIRA POSIÇÃO DO CARACTERE NA STRING
REVERSE - REVERTE A ORDEM DE LEITURA DOS CARACTERES DA DIREITA PRA ESQUERDA 
*/

CREATE DATABASE SIGA;
USE SIGA;
--DROP TABLE CLIENTE
CREATE TABLE CLIENTE(
CODIGO INT NOT NULL IDENTITY CONSTRAINT PK_CLIENTE PRIMARY KEY,
NOME VARCHAR (100) NOT NULL,
CPF CHAR (14) NOT NULL CONSTRAINT UK_CLIENTE_CPF UNIQUE,
RENDA NUMERIC (10,2) NOT NULL CONSTRAINT DF_CLIENTE_RENDA DEFAULT 0,
SEXO VARCHAR (9) NOT NULL CONSTRAINT CK_CLIENTE_SEXO
		CHECK(SEXO IN ('MASCULINO','FEMININO','NÃO INFORMADO')),
ANIVERSARIO DATE NULL
)

INSERT INTO CLIENTE (NOME, CPF, SEXO) VALUES
('MARIA JOSÉ', '123.456.789-02','FEMININO');

SET DATEFORMAT YMD
INSERT INTO CLIENTE (NOME, CPF, SEXO, RENDA, ANIVERSARIO) VALUES
('  JOSÉ MARIA  ', '263.130.449-22','FEMININO',3200.50,'2000-02-11');

--SP_HELP CLIENTE;

SELECT NOME, CPF FROM CLIENTE
--SELECT SUBSTRING('PIRACICABA',3,4)--VÁ ATÉ A POSIÇÃO 3, SELECIONE 4 CARACTERES

SELECT CPF, SUBSTRING(CPF,1,3) + 
			SUBSTRING (CPF,5,3) +
			SUBSTRING (CPF,9,3) +
			SUBSTRING (CPF,13,2) AS CPF_FORMATADO FROM CLIENTE
--FORMATANDO O RECEBIMENTO DE CPF SEM OS CARACTERES ESPECIAIS

--SELECT CHARINDEX('C','FATEC')
--SELECIONAR QUAL A POSIÇÃO DO "C" DENTRO DA PALAVRA FATEC

SELECT CHARINDEX(' ','PALAVRA DE NOME')-1 
--SELECIONA O PRIMEIRO NOME DA PALAVRA
--POIS MARCA AS POSIÇÕES ANTES DO PRIMEIRO ESPAÇO EM BRANCO

SELECT SUBSTRING (NOME,1,CHARINDEX(' ',NOME)-1)
FROM CLIENTE

SELECT SUBSTRING (UPPER(TRIM(NOME)),1,CHARINDEX(' ', UPPER(TRIM(NOME)))-1)
FROM CLIENTE
--APRENDENDO A RETORNAR O NOME DO CLIENTE DIRETO NA TABELA JÁ FORMATADO

SELECT REVERSE(SUBSTRING (REVERSE(UPPER(TRIM(NOME))),1,
	   CHARINDEX(' ', REVERSE(UPPER(TRIM(NOME))))-1)) + ', ' + 
	   SUBSTRING(UPPER(TRIM(NOME)),1,CHARINDEX(' ',UPPER(TRIM(NOME)))-1)
FROM CLIENTE
--RETORNANDO NOME E SOBRENOME, SENDO SOBRENOME NA FRENTE DO NOME:
-- FORMATO: "SCURSONI, RAPHAEL".

SELECT RENDA, 
	  STR((RENDA * 0.08),8,2) AS FGTS, 
	  STR((RENDA / 5.53),8,2) AS 'RENDA ESCOLAR'
FROM CLIENTE 
WHERE RENDA > 0
/* TRABALHANDO COM DATAS
DATEPART - RETORNA PARTE DE UMA DATA
DATENAME - RETORNA O NOME DA DATA(MÊS, DIA DA SEMANA)
DATEADD - ADICIONA A PARTE INFORMADA NA DATA
DATEDIFF - DIFERENÇA ENTRE DUAS DATAS
*/
SELECT DATEADD(WK,-40,GETDATE()) 
-- DESCOBRINDO A DATA QUE ESTAVAM FAZENDO O BEBÊ QUE NASCEU HOJE

SELECT DATEDIFF(DD,'2021-01-01', GETDATE()) 
--DATA DO COMEÇO DO ANO ATÉ HOJE, QUANDOS DIAS DERAM

SELECT DATEDIFF(YYYY,ANIVERSARIO, GETDATE()) FROM CLIENTE
--DESCOBRINDO A IDADE DAS PESSOAS

SELECT STR(DATEPART(DD, ANIVERSARIO),2) +'/'+
	   STR(DATEPART(MM, ANIVERSARIO),2) +'/'+
	   STR(DATEPART(YYYY, ANIVERSARIO),4)
FROM CLIENTE 
WHERE ANIVERSARIO IS NOT NULL

SELECT GETDATE() --RETORNA O DIA DE HOJE
SET LANGUAGE PORTUGUESE -- RETORNA A DATA NO INDIOMA SELECIONADO
SELECT DATENAME(DW,GETDATE())

SELECT 
	CODIGO, UPPER(TRIM(NOME)) AS NOME, SEXO 
FROM 
	CLIENTE
FOR XML AUTO, ROOT('CLIENTES'), ELEMENTS
